variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  # PATH: /usr/global/tools/ruby/toss_3_x86_64_ib/bin:$PATH
  GEM_HOME: /usr/global/tools/ruby/toss_3_x86_64_ib/lib/ruby/gems

before_script:
  - echo $PATH
  - echo $GEM_HOME
# NOTE: Jeff Long (jwlong) owns the /collab/usr/global ruby install and only he should install things
#   - bundle install

test:
  stage: test
  tags:
  - shell
  script:
  - export PATH=/usr/global/tools/ruby/toss_3_x86_64_ib/bin:$PATH
  - echo $PATH
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  # except:
  # - main

pages:
  stage: deploy
  tags:
  - shell
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main
