variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  BUNDLE: /usr/global/tools/ruby/toss_3_x86_64_ib/bin/bundle
  GEM_HOME: /usr/global/tools/ruby/toss_3_x86_64_ib/lib/ruby/gems

# before_script:
# NOTE: Jeff Long (jwlong) owns the /collab/usr/global ruby install and only he should install things
#   - $BUNDLE install

test:
  stage: test
  script:
  - $BUNDLE exec jekyll build -d test
  artifacts:
    paths:
    - test
  # except:
  # - main

pages:
  stage: deploy
  script:
  - $BUNDLE exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main
