author: "Livermore Computing <lc-hotline@llnl.gov>"
title: LLNL HPC Tutorials
description: "Lawrence Livermore National Laboratory Software Portal"
remote_theme: LLNL/Jekyll-LLNL-Theme@main

url: "https://hpc-tutorials.llnl.gov"
repo_url: "https://github.com/LLNL/hpc-tutorials"

# LLNL Piwik Analytics https://analytics.llnl.gov
# piwik_id: 250

# Google Analytics ID
# google_analytics:
#   tracking_id: UA-75179431-1

# Twitter username (used by jekyll-seo-tag)
twitter:
  username: llnl_opensource  # llnl_computing ?

# GitHub Metadata -- https://github.com/jekyll/github-metadata
repository: llnl/hpc-tutorials
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

kramdown:
  auto_ids: true

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       permalink: "/news/:year/:month/:day/:title/"

permalink: pretty

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - README.md
    - Makefile
    - build
